// The sequence of triangle numbers is generated by adding the natural numbers. 
// So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
// Let us list the factors of the first seven triangle numbers:
// 1: 1
// 3: 1,3
// 6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number to have over five divisors.
// What is the value of the first triangle number to have over five hundred divisors?

var findHDTN = function(num) {
  var sumOfNaturalNums = 17907120;
  var index = 5984;

  while(true){
    index++;
    sumOfNaturalNums += index;
    if( sumOfNaturalNums % 2 === 0 ){
      var factors = findFactors(sumOfNaturalNums);

      if( factors > num ){
        return [sumOfNaturalNums, index, factors];
      }    
    }
  }
};

var findFactors = function(num) {
  var factors = 3;

  for( var i = 2; i <= num/3; i++ ){
    if( num % i === 0 ){ factors += 1; }
  }

  return factors;
};

console.log(findHDTN(500));